/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:15cdf0d4-6f4c-48c8-bf67-727f3914a2b3",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_gFljhS5bG",
    "aws_user_pools_web_client_id": "204nc9mautc0lj07jujddtapif",
    "oauth": {}
};


export default awsmobile;
